### ISSUE TITLE
Missing License for Cartesia Python SDK

### ISSUE THREAD

**Issue by bionicles** [cartesia-ai/cartesia-python#45]
Hi, could you please post a license?

Suggestion: since this is an SDK, could we please use one compatible with the Rust project?

Most Rust crates use Apache-2.0 OR MIT, this saves you folks and your users' time
https://opensource.org/licenses?categories=popular-strong-community
https://www.rust-lang.org/policies/licenses

Benefit: Clarity / Simplicity about ability to use Cartesia's Python SDK for commercial projects. Since this is only a Python SDK and not your model, an open source license on the SDK would only imply the SDK is usable in work projects and wouldnt' imply any changes to licenses for other parts of your systems not included in this code repo. (Not a lawyer but I'm 99.999% confident this is how it works)

Then paying Cartesia customers can feel confident we can use these voiceovers for e.g. startup explainers, guides, that kind of thing

**Comment by kbrgl** [comment]
The SDK is licensed under the MIT license. We'll add a LICENSE file today. Thanks for flagging!
